### PR TITLE
Update Debian dependencies

### PR DESCRIPTION
**Pull request by vaitkus**
This updates the Debian dependencies for this specific branch as discussed in https://github.com/Materials-Consortia/OPTIMADE/pull/445#issuecomment-1885207620.

### CODE REVIEW

**Comment by vaitkus** [comment]
@rartino, I do not seem to have sufficient permissions to request you as a reviewer on this PR, so I will ping you this way just in case GitHub did not properly inform you.

**Comment by rartino** [comment]
@vaitkus Looks good so far, but incomplete? The preamble of  process_schemas.py lists the dependencies for three different package systems:

  - apt: `apt install python3-yaml python3-jsonschema python3-markdown python3-mdx-math python3-pygments`
  - pip: `pip install PyYAML jsonschema python-markdown python-markdown-math pygments`
  - conda: `conda install python=3 pyyaml jsonschema markdown python-markdown-math pygments`

Where `apt` was tested on recent Ubuntu. Can you check on Debian 10 if these packages work/make sense?: `python3-yaml python3-jsonschema python3-markdown python3-mdx-math python3-pygments`, and if so, add them to this PR. (And maybe indicate with a comment that they are subdependencies of optimade-property-tools if this is OK to do in this dependency format).

Or, just a thought, should we add a `dependencies` to optimade-property-tools and just have this one call that one?

**Comment by vaitkus** [comment]
> Looks good so far, but incomplete?

Yes, I didn't do a very thorough job (I simply added the dependency that was missing on my system to make things work). Just tested the updated dependency list on a fresh install of Debian 10/11/12 and caught a few additional missing ones.

> Where apt was tested on recent Ubuntu. Can you check on Debian 10 if these packages work/make sense?: python3-yaml python3-jsonschema python3-markdown python3-mdx-math python3-pygments, and if so, add them to this PR. (And maybe indicate with a comment that they are subdependencies of optimade-property-tools if this is OK to do in this dependency format).

All packages exist in Debian 10 (and most of them actually depend on `python3-mdx-math`). I have updated the installer as requested. However, while the `make schemas` command works on Debian 11 and Debian 12, on Debian 10 the command eventually fails with the following message:
```
WARNING: JSON Schema Python library is not aware of the Draft202012 standard. It is probably too old. Will validate using default validator.
Validation of data failed. Error details:
- RefResolutionError: Validation: attempt to fetch remote schema over the internet blocked: meta/core (/home/antanas/src/OPTIMADE/dependencies/submodules/optimade-property-tools/src/process_schemas/process_schemas.py line 1471 triggered in: /usr/lib/python3/dist-packages/jsonschema/validators.py at line 385).
```
This might be due to an older version of `jsonschema` library not being able to handle something. However, I am not sure its worth investigating much further given that the official support for Debian 10 will end in 6 months.

> Or, just a thought, should we add a dependencies to optimade-property-tools and just have this one call that one?

We could also go this way. But then an additional check and a warning should also be added to detect situations when the submodule is not yet initialised.

**Comment by rartino** [comment]
> "WARNING: JSON Schema Python library is not aware of the Draft202012 standard. It is probably too old. Will validate using default validator."

This warning message means exactly what it says. Surprisingly recent versions of the jsonschema Python package are needed. But, I've largely managed to validate the schemas successfully despite this warning.

> - RefResolutionError: Validation: attempt to fetch remote schema over the internet blocked: meta/core (/home/antanas/src/OPTIMADE/dependencies/submodules/optimade-property-tools/src/process_schemas/process_schemas.py line 1471 triggered in: /usr/lib/python3/dist-packages/jsonschema/validators.py at line 385).

Well, if it works with newer versions, that is probably it. (Maybe the feature to supply offline schemas has been improved since the Debian-10 version.) The workaround is to pip (or conda) install a more recent version.

**Pull request merged**
